name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Start SSH Agent and Add Key
        run: |
          mkdir -p ~/.ssh  # Create .ssh directory if it doesn't exist
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | awk 'NF { print $$0 }' > ~/.ssh/id_rsa  # Save the private key
          chmod 600 ~/.ssh/id_rsa  # Restrict permissions on the key
          eval "$(ssh-agent -s)"  # Start the SSH agent
          ssh-add ~/.ssh/id_rsa  # Add the private key to the agent

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts  # Add remote host to known_hosts

      - name: Pull changes on Server
        env:
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PATH: "/var/www/html/break-tech"
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH && git pull origin main"
